c.auto_save.session = True
c.content.autoplay = False
c.content.canvas_reading = False
c.content.cookies.accept = 'no-3rdparty'
c.content.webgl = False
c.content.webrtc_ip_handling_policy = 'default-public-interface-only'
c.session.lazy_restore = True
c.tabs.background = True
c.tabs.position = 'left'
# c.window.hide_decoration = False
