[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[gcloud]
disabled = true

[c]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[terraform]
symbol = "󱁢 "
