require('user.plugins')
require('user.options')
require('user.keymaps')
require('user.colorscheme')
require('user.autocommands')

require('user.statusline')
require('user.treesitter')
require('user.comment')
require('user.indentline')
require('user.gitsigns')
require('user.telescope')
require('user.lsp')
require('user.cmp')
require('user.leap')
require('user.symbols-outline')
require('user.hydra')
require('user.autopairs')
